openapi: 3.0.3
info:
  title: Flex Page Example
  contact:
    email: glebmachine@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: page
    description: Апи наборных страниц
paths:
  /page:
    get:
      tags:
        - page
      description: Выдает страницу с наборными блоками
      operationId: getPage
      responses:
        '200':
          description: Страница с наборными блоками
          content:
            application/json:
              schema:
                type: array

                items:
                  $ref: '#/components/schemas/PageItem'

components:
  schemas:
    PageItem:
      type: object
      properties:
        objectId:
          type: integer
          description: Айдишник наборного блока
        objectType:
          type: string
          description: Тип наборного блока
